# Generated by Django 4.2.3 on 2023-07-22 11:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="limited",
            field=models.BooleanField(
                default=False, verbose_name="If the item is limited or not."
            ),
        ),
    ]
