# Generated by Django 4.2.3 on 2023-07-22 12:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_catalog", "0002_product_limited"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="banner",
            field=models.BooleanField(default=False, verbose_name="Show on Banner?"),
        ),
        migrations.AlterField(
            model_name="product",
            name="limited",
            field=models.BooleanField(default=False, verbose_name="Limtied Item?"),
        ),
    ]
