# Generated by Django 4.2.3 on 2023-07-22 12:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_catalog", "0003_product_banner_alter_product_limited"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="sale",
            field=models.BooleanField(default=False, verbose_name="Is item on sale?"),
        ),
    ]
