# Generated by Django 4.2.3 on 2023-07-22 13:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("app_catalog", "0004_product_sale"),
    ]

    operations = [
        migrations.CreateModel(
            name="BasketItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=8, verbose_name="Price"
                    ),
                ),
                ("count", models.IntegerField(verbose_name="Count")),
                ("date", models.DateTimeField(auto_now_add=True, verbose_name="Date")),
                ("freeDelivery", models.BooleanField(verbose_name="Free Delivery")),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app_catalog.category",
                        verbose_name="Category product belongs to",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app_catalog.product",
                        verbose_name="Product ID",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User's cart",
                    ),
                ),
            ],
            options={
                "verbose_name": "Basket Item",
                "verbose_name_plural": "Basket Items",
            },
        ),
    ]
