# Generated by Django 4.2.3 on 2023-07-29 10:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_basket", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="basketitem",
            name="count",
        ),
        migrations.RemoveField(
            model_name="basketitem",
            name="date",
        ),
        migrations.RemoveField(
            model_name="basketitem",
            name="freeDelivery",
        ),
        migrations.AddField(
            model_name="basketitem",
            name="quantity",
            field=models.IntegerField(default=1, verbose_name="Quantity"),
            preserve_default=False,
        ),
    ]
