# Generated by Django 4.2.3 on 2023-07-29 13:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_basket", "0002_remove_basketitem_count_remove_basketitem_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="basketitem",
            name="category",
        ),
    ]
