# Generated by Django 4.2.3 on 2023-07-31 12:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_basket", "0003_remove_basketitem_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="basketitem",
            name="quantity",
            field=models.PositiveIntegerField(verbose_name="Quantity"),
        ),
    ]
