# Generated by Django 4.2.3 on 2023-07-31 12:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_orders", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={
                "ordering": ("-createdAt",),
                "verbose_name": "Order",
                "verbose_name_plural": "Orders",
            },
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_price",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="Delivery Cost"
            ),
        ),
        migrations.AddField(
            model_name="orderproduct",
            name="price",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=8, verbose_name="Price"
            ),
        ),
        migrations.AddField(
            model_name="orderproduct",
            name="quantity",
            field=models.PositiveIntegerField(default=1, verbose_name="Quantity"),
        ),
        migrations.AlterField(
            model_name="order",
            name="deliveryType",
            field=models.CharField(
                choices=[
                    ("normal", "Normal Delivery"),
                    ("express", "Express Delivery"),
                ],
                default="normal",
                max_length=50,
                verbose_name="Delivery Type",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="paymentType",
            field=models.CharField(
                choices=[
                    ("card", "Payment with Card"),
                    ("different_card", "Payment with Somebody Else's Card"),
                ],
                default="card",
                max_length=50,
                verbose_name="Payment Type",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Status"
            ),
        ),
    ]
