# Generated by Django 4.2.3 on 2023-08-02 04:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("app_orders", "0003_alter_orderproduct_order"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.CharField(max_length=16, verbose_name="Payment Number"),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Cardholder Name"),
                ),
                (
                    "month",
                    models.CharField(max_length=2, verbose_name="Expiration Month"),
                ),
                (
                    "year",
                    models.CharField(max_length=4, verbose_name="Expiration Year"),
                ),
                ("code", models.CharField(max_length=8, verbose_name="Security Code")),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app_orders.order",
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment",
                "verbose_name_plural": "Payments",
            },
        ),
    ]
